### ISSUE TITLE
Proposal Review 11/7/18

### ISSUE THREAD

**Issue by BCrawfordScott** [purabshah8/kantrello#1]
### MVP List 
- Looks really good.  One thing to think about: assigning cards to different lists.  There is a clear form to do this in what could be the `card show` page of a card on trello.  That should be the functionality we focus on building.  As a Bonus, you could incorporate the react drag and drop library (`react-dnd`) to allow users to click and drag cards into a new list, but that could take some time and playing around.  We can talk about it more if you like.

### Schema 
- What do you mean by position in lists and cards?  Is it the order of the lists as they are presented?  
- [x] Change `board_users` to `board_shares` for readability and convention.

- Overall looks good. There is a lot of functionality that you won't need to build out, but that also means your styling will be a little different.  That's totally ok, just do you best to style as true to the actual app as possible with those different features omitted.  If you have any questions on specific things we can work together to find what makes the most sense.

**Comment by purabshah8** [comment]
### MVP List

- Okay, I will add moving cards onto my MVP list.  I definitely want to incorporate drag and drop functionality using react-dnd. I have skimmed the react-dnd overview [here](http://react-dnd.github.io/react-dnd/docs/overview) and will check out the tutorial. Are there other resources I can use? 

### Schema

- Yes, position is the order in which to display the list items and card items.

- Would it be preferable to have css placeholders for the functionality (e.g. search bar) that won't be implemented or be omitted entirely?

**Comment by BCrawfordScott** [comment]
- react-dnd:  I've never used the library, but any tutorials you can find and the docs will be your best resources.  I'll ask around and see if I can find anything else, but it sounds like you're on the right track already. 

- CSS Placeholder:  You will definitely want to design in terms of the same amount of space, but (big but) we should never have inactive links, buttons, inputs, etc in our apps.  It's better to have blank space in an app than a fake button.
