### ISSUE TITLE
Review 11/14

### ISSUE THREAD

**Issue by BCrawfordScott** [purabshah8/kantrello#2]
- [x] Add links to sign up and log in on body of landing page.
- [x] Add a footer as a placeholder so there isn't whitespace on the bottom of the page.  Feel free to put links to your github, your portfolio site (in the future) and also a link to actual trello for fun in the footer.
- [x] Add a favicon for the page tab (optional but looks really nice).
- [x] Styling for both login and sign up
- [x] Add log out button after sign in

Don't forget to make sure you're handling errors for bad logins.

Great work!

**Comment by purabshah8** [comment]
Finished all the above.
