### ISSUE TITLE
Auth Review 11/15

### ISSUE THREAD

**Issue by BCrawfordScott** [purabshah8/kantrello#3]
- [x] Typo on Homepage: "Kantrello allows you work" --> "Kantrello allows you to work" 
- [x] Remove overflow-y scroll from landing page on the Kantrello Description.  No need for it, just go ahead and make the html element taller.
- [x] Remove the empty space until you are able to fill it with an actual screenshot/demo.  It will look cleaner while you build that part out.
- [x] Add more styling to errors:   It looks like Trello's styling includes a red box with the text in white.  That's as much as you need.

Otherwise this looks great.  Good functionality, excellent work.

**Comment by purabshah8** [comment]
Fixed all but the overflow-y scroll issue. I'm not sure what you are talking about. Can you please explain?

**Comment by purabshah8** [comment]
Never mind, I found out what you meant when I viewed it on a different screen and fixed it.
